<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>IATec.Shared.Behaviors</PackageId>
		<Authors>IATec | Solutions | Platform Team</Authors>
		<Description>Project developed to help IATec teams to develop their projects faster.</Description>
		<Copyright>@IATec Solutions</Copyright>
		<RootNamespace>IATec.Shared.Behaviors</RootNamespace>
		<Version>1.0.3</Version>
		<PackageIconUrl>https://assets-services-dev.sdasystems.org/images/icons/standard.library.icon.png</PackageIconUrl>
		<PackageIcon>icon.png</PackageIcon>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
		<Title>IATec Shared Behaviors</Title>
		<PackageProjectUrl>https://github.com/iatecbr/IATec.Shared.Net.Behaviors</PackageProjectUrl>
		<PackageLicenseUrl>https://github.com/iatecbr/IATec.Shared.Net.Behaviors/blob/5b81dea6b3c101aab9122abfad44cb94e5a30480/LICENSE</PackageLicenseUrl>
		<RepositoryUrl>https://github.com/iatecbr/IATec.Shared.Net.Behaviors</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<PackageTags>net</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\resources\icons\icon.png" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentResults" Version="3.16.0" />
		<PackageReference Include="MediatR" Version="12.2.0" />
		<PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="9.0.8" />
		<PackageReference Include="IATec.Shared.Domain" Version="1.0.1" />
	</ItemGroup>
</Project>
